                                                                          ICP-2

Q1

In [8]:
class Employee:
    employee_count = 0
    total_salary = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1
        Employee.total_salary += salary

    @classmethod
    def average_salary(cls):
        if cls.employee_count > 0:
            return cls.total_salary / cls.employee_count
        return 0

    def display_employee(self):
        return f"Employee: {self.name}, Family: {self.family} Department: {self.department}, Salary: {self.salary}"

class FulltimeEmployee(Employee):
    ft_employee_count = 0
    ft_total_salary = 0

    def __init__(self, name, family, salary, department):
        super().__init__(name, family, salary, department)
        FulltimeEmployee.ft_employee_count += 1
        FulltimeEmployee.ft_total_salary += salary

    @classmethod
    def average_salary(cls):
        if cls.ft_employee_count > 0:
            return cls.ft_total_salary / cls.ft_employee_count
        return 0

    def display_employee(self):
        return f"Fulltime Employee: {self.name}, Family: {self.family} Department: {self.department}, Salary: {self.salary}"

# Creating instances
emp1 = Employee("Sainath", "Bodige", 100000, "IT Development")
emp2 = Employee("Suman", "D", 95000, "Marketing")
ft_emp1 = FulltimeEmployee("Rohit", "Reddy", 70000, "Human Resource")
ft_emp2 = FulltimeEmployee("Priya", "K", 80000, "Finance")

# Displaying information
print(emp1.display_employee())
print(emp2.display_employee())
print(ft_emp1.display_employee())
print(ft_emp2.display_employee())

# Displaying average salaries and counts
print(f"Average Salary of Employees: {Employee.average_salary()}")
print(f"Number of Employees: {Employee.employee_count}")
print(f"Average Salary of Fulltime Employees: {FulltimeEmployee.average_salary()}")
print(f"Number of Fulltime Employees: {FulltimeEmployee.ft_employee_count}")


Employee: Sainath, Family: Bodige Department: IT Development, Salary: 100000
Employee: Suman, Family: D Department: Marketing, Salary: 95000
Fulltime Employee: Rohit, Family: Reddy Department: Human Resource, Salary: 70000
Fulltime Employee: Priya, Family: K Department: Finance, Salary: 80000
Average Salary of Employees: 86250.0
Number of Employees: 4
Average Salary of Fulltime Employees: 75000.0
Number of Fulltime Employees: 2


Q2

In [7]:
import numpy as np

# Create random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

# Reshape the array to 4 by 5
reshaped_array = random_vector.reshape(4, 5)
#print(reshaped_array)
# Replace the max in each row by 0
reshaped_array[reshaped_array == reshaped_array.max(axis=1, keepdims=True)] = 0

reshaped_array


[[ 1.24267852  4.63433975 10.696671   10.05391008 16.22260334]
 [15.34202854 16.55522505  9.00945359 15.47759427 10.18718611]
 [ 4.32081335 14.35795837 15.26860031  3.95295235  5.21960454]
 [ 5.70878765  8.70033882  5.42154667  4.55940918  2.0143742 ]]


array([[ 1.24267852,  4.63433975, 10.696671  , 10.05391008,  0.        ],
       [15.34202854,  0.        ,  9.00945359, 15.47759427, 10.18718611],
       [ 4.32081335, 14.35795837,  0.        ,  3.95295235,  5.21960454],
       [ 5.70878765,  0.        ,  5.42154667,  4.55940918,  2.0143742 ]])